### ISSUE TITLE
On.Terraria.Projectile.GetAlpha: Illegal One-Byte Branch

### ISSUE THREAD

**Issue by chatrat12** [0x0ade/MonoMod#37] opened 2019-02-03 07:34 UTC
Trying too hook into `Projectile.GetAlpha`, getting error below.

Using TerrariaHooks v0.16

## Code
```cs
On.Terraria.Projectile.GetAlpha += (orig, self, color) =>
{
    return orig(self, color);
};
```
## Error
![image](https://user-images.githubusercontent.com/251682/52174016-21db3780-275c-11e9-8c27-8770d1d3074c.png)

**Comment by chatrat12** [comment] 2019-02-03 07:41
Same with
```cs
IL.Terraria.Projectile.GetAlpha += (il) =>
{
    var cursor = il.At(0);
};
```

**Comment by 0x0ade** [comment] 2019-02-03 09:54
Are you using the latest version of MonoMod, specifically the latest devbuild? Visit the the [build log](https://0x0ade.visualstudio.com/MonoMod/_build?definitionId=1), select the latest (top) build, go to the summary tab, download the net35 artifact and put all relevant files into the Terraria folder. It _should_ then load the latest version of MonoMod instead of loading the version bundled with tML.

**Comment by 0x0ade** [comment] 2019-02-03 14:08
Nevermind, I just managed to replicate it using MonoMod 19.2.3.1. Debugging it right now.

**Comment by 0x0ade** [comment] 2019-02-03 23:44
The issue is now fixed here.

Can you please test it using the following build artifact?

https://0x0ade.visualstudio.com/e07cb5e7-fa7f-457d-982b-3323979ed1b7/_apis/build/builds/209/artifacts?artifactName=net35&api-version=5.1-preview.5&%24format=zip

You only need to place `MonoMod.Utils.dll` and `MonoMod.RuntimeDetour.dll` into the Terraria directory.

**Comment by 0x0ade** [comment] 2019-02-05 22:55
Nevermind, I just realized that you're using TerrariaHooks, not tML 0.11 😅 

![image](https://user-images.githubusercontent.com/1200380/52309556-cd74c980-29a0-11e9-8992-c6dca67ded4d.png)

Please report back whether you're still experiencing the issue with TerrariaHooks 0.17 or if it's fixed for you as well.

**Comment by 0x0ade** [comment] 2019-02-06 15:08
Resolved on the tML Discord.

**Closed** 2019-02-06 15:08 UTC
