### ISSUE TITLE
MonoModOriginalName being added to the orig_Method

### ISSUE THREAD

**Issue by iamwyza** [0x0ade/MonoMod#16] opened 2017-11-15 06:57 UTC
If you have a setup like:

```csharp
public void orig_MyMethod(){ }

public void MyMethod() {
//do stuff
orig_MyMethod()
}
```

MonoMod adds [MonoModOriginalName] on the orig_MyMethod but does so without the ("MyMethod") constructor on the attribute.  This is syntactically invalid and if you try to edit the resulting assembly with something like dnspy, you can't compile.

I fixed this in the monomod code using:

MonoModder.cs:1331
```csharp
                // Fix MonoModOriginalName should not be put onto the original methods as it would add them without the argument.
                List<CustomAttribute> toRemove = origMethod.CustomAttributes.Where(x => x.AttributeType.Name == "MonoModOriginalName").ToList();
                
                foreach (CustomAttribute attrib in toRemove)
                    origMethod.CustomAttributes.Remove(attrib);
```

**Comment by 0x0ade** [comment] 2017-11-15 11:57
Oh, that's caused by me confusing two attributes. Sorry 😅 

Original methods should get the `[MonoModOriginal]` attribute (parameter-less), while the patched method should get `[MonoModOriginalName(originalName)]` if it doesn't already have it.

I don't have a stable "modding test case" set up at the moment, but I'll attempt to fix it anyway, assuming that if it will work for you, it'll work for everyone.

Thanks!

**Comment by 0x0ade** [comment] 2017-11-15 14:05
Huh, weirdly enough, what I just described _should_ be happening already.

The following line affects the orig_ clone method:
https://github.com/0x0ade/MonoMod/blob/f40c12266d7fac704ca07806c68bb4c2780179be/MonoMod/MonoModder.cs#L1329

The following lines affect the modded method:
https://github.com/0x0ade/MonoMod/blob/f40c12266d7fac704ca07806c68bb4c2780179be/MonoMod/MonoModder.cs#L1390-L1394

I'll see if I can find out what's going wrong here...

**Comment by 0x0ade** [comment] 2017-11-15 14:10
Turns out `GetMonoModOriginalNameCtor()` cached the resulting `MonoMod.MonoModOriginalName` in `_mmOriginalCtor`, not `_mmOriginalNameCtor`, causing this issue. Should be fixed with the next commit

**Closed** 2017-11-15 14:24 UTC
